### ISSUE TITLE
Integration from cocoapods don't work out of the box

### ISSUE THREAD

**Issue by ousabasa** [paulrolfe/PARTagPicker#1]
You still have to search for the nibs and include them in the project, must be done programatically or included in pod bundle.

Thanks for your great work :)

**Comment by paulrolfe** [comment]
Thanks for letting me know, I'll try to fix that this weekend.

—

**Comment by paulrolfe** [comment]
Finally got this done. I'm closing the issue, but please confirm that it works for you as well. Thanks again.
