### ISSUE TITLE
Need dynamic search input text hashtag

### ISSUE THREAD

**Issue by mathiarasan24** [paulrolfe/PARTagPicker#10]
Hi,

You did great job!

Here what I need, My design look like this and search suggestion from API so it's dynamic based on textfield text. So I edit source code like this

```
-(void)addDynamicTextFromSearch:(NSString *)newString
{
    [self.chosenTags addObject:newString];
    NSIndexPath *addedPath = [NSIndexPath indexPathForItem:self.chosenTags.count inSection:0];
    [self.chosenTagCollectionView insertItemsAtIndexPaths:@[addedPath]];
    [self.chosenTagCollectionView scrollToItemAtIndexPath:addedPath atScrollPosition:UICollectionViewScrollPositionCenteredHorizontally animated:YES];
}
```

And I got output like this two placeholder when I tap text from my API output.
![screen shot 2016-04-12 at 8 43 55 pm](https://cloud.githubusercontent.com/assets/11555734/14465199/b008e2be-00ef-11e6-878e-347aaf0b90c8.png)

When I scroll that get correct text(horizontally) which I selected, with extra placeholder textView like this
![screen shot 2016-04-12 at 8 44 27 pm](https://cloud.githubusercontent.com/assets/11555734/14465283/ff4471a4-00ef-11e6-99ad-3510bcc8a860.png)

At init method I didn't give any `allTag` to search when user type. I want insert dynamic text based on my API search text.

```
self.tagPicker = [[PARTagPickerViewController alloc] init];

    self.tagPicker.view.frame = CGRectMake(0, 0, self.tagPickerView.frame.size.width, self.tagPickerView.frame.size.height); // self.tagPickerView.frame;   //78 is the fully expanded height.

    [self.tagPicker.view.layer setCornerRadius:CGRectGetHeight(self.tagPicker.view.frame) / 2];

    self.tagPicker.view.layer.borderColor = [UIColor KSCloudyBlueColor].CGColor;

    self.tagPicker.view.layer.borderWidth = 1.0;

    self.tagPicker.view.backgroundColor = [UIColor clearColor];

    self.tagPicker.view.autoresizingMask = UIViewAutoresizingFlexibleWidth;

    self.tagPicker.delegate = self;

    self.tagPicker.allTags = @[];

    //optionally allow new tags to be made
    self.tagPicker.allowsNewTags = YES;


    [self addChildViewController:self.tagPicker];

    [self.tagPickerView addSubview:self.tagPicker.view];
```

My init code

Is this possible?

Thanks in advance :)

**Comment by paulrolfe** [comment]
@mathiarasan24 Hey, I somehow missed this. Are you still looking for a solution on this?

**Comment by mathiarasan24** [comment]
@paulrolfe Thanks for reply. I now didn't. Came with some other way to use your code.
