### ISSUE TITLE
Index 0 beyond bounds for empty array

### ISSUE THREAD

**Issue by ostanik** [paulrolfe/PARTagPicker#13]
This bug is caused when the the textfieldEnabled is set to false and occurs a touch into de textField, the method  - (void)removeChosenTagFromIndexPath:(NSIndexPath *)indexPath is throwing the error:  index 0 beyond bounds for empty array.

Thats because the array chosenTags is not set. 

i made a pull request with an hotfix, but i don't know if is the better approach.

**Comment by paulrolfe** [comment]
Looks good, that makes it safer for sure. I merged it.
