### ISSUE TITLE
crash after deleting tags with the same name

### ISSUE THREAD

**Issue by viktorwillmann** [paulrolfe/PARTagPicker#16]
implemented it in swift 2.3, it crashes wenn you insert two tags with the same text and try to delete one.

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (2) must be equal to the number of items contained in that section before the update (4), plus or minus the number of items inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).

**Comment by ostanik** [comment]
i solved the issue on the [PR - #17](https://github.com/paulrolfe/PARTagPicker/pull/17)
