### ISSUE TITLE
just curious if there will be an update to swift 3.0 support?

### ISSUE THREAD

**Issue by taijizhu** [paulrolfe/PARTagPicker#22]

**Comment by paulrolfe** [comment]
Yeah, will do when I have some time. It shouldn't be a big deal since the library is on obj-c. Please submit a PR if you want to work on it

**Comment by paulrolfe** [comment]
Hey, I just tried it out and it already works on swift 3, at least with version `1.2.3`. Run `pod install` again, and check your project settings. But it should be fine.
