### ISSUE TITLE
Can't order tags

### ISSUE THREAD

**Issue by daliadanila** [paulrolfe/PARTagPicker#26]
Whatever the order the tags are in, it seems that they will always be in reverse alphabetical order when they show up.

Is there a workaround that?

Thanks,
Dalia

**Comment by paulrolfe** [comment]
It's true, it will sort them.

The workaround would be to comment out lines 149 and 150 in `PARTagPickerViewController.m`

The fix would be submit a Pull Request that enables an optional custom sorter.
