### ISSUE TITLE
Use in UITableViewCell

### ISSUE THREAD

**Issue by lukkigi** [paulrolfe/PARTagPicker#3]
Hello,
I need to use this in a custom UITableViewCell. I've tried putting the adding the picker.view as a subview to the cell and setting the delegate to the UITableViewController, but the picker is just blank with the background color showing. Any advice?

```
let tagPicker = PARTagPickerViewController()
tagPicker.view.backgroundColor = UIColor.whiteColor()
tagPicker.view.frame = CGRect(x: 0, y: 0, width: CGRectGetWidth(cell.bounds), height: COLLECTION_VIEW_HEIGHT)
tagPicker.view.autoresizingMask = UIViewAutoresizing.FlexibleWidth
tagPicker.delegate = self
tagPicker.allTags = ["hurfi", "durfi"]
tagPicker.allowsNewTags = true
tagPicker.chosenTags = NSMutableArray(array: queries)
tagPicker.visibilityState = .TopAndBottom

self.addChildViewController(tagPicker)
cell.paddingView.addSubview(tagPicker.view)
```

**Comment by paulrolfe** [comment]
Apologies for not replying sooner. As you may have already discovered, there are some issues around using this pod with swift. Basically it isn't loading the IBOutlets. I'm trying to figure it out, thanks for letting me know.

**Comment by paulrolfe** [comment]
FYI. Temporary solution is to drag the .xib files into your project. I'll update the podspec such that it will work with swift now -- it was a module issue.

UPDATE: Ok, updated pod is ready. Thanks for your patience.
