### ISSUE TITLE
Feature Request (From Ildar)

### ISSUE THREAD

**Issue by paulrolfe** [paulrolfe/PARTagPicker#7]
Good Day! 
I working with your library and wanna show tagPicker in each cell in my TableView ('cause it scrollable and easy to use), BUT there a some problem: every time to ends of tags adding textField (I see that it's for creating new tags, but when I show tags in tableView i don't want create some new tags there, so could you help me and explain where i can change some pice of code to create TagPicker without textField in the end. 

With respect, 
…

P.S. I tried to do it by my self, but in collectionView_cellForItemAtIndexPath throw exception when I tried to delete, or edit place when you add textField.

**Comment by CavalcanteLeo** [comment]
+1

**Comment by paulrolfe** [comment]
New properties were added to make this feature possible. See the PR ☝️
