### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by TofPlay** [paulrolfe/PARTagPicker#9]
Hi,
It's will be great to add [Carthage](https://github.com/Carthage/Carthage) support

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://realm.io/news/swift-dependency-management-with-carthage/)
- [Carthage Tutorial: Getting Started](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started)
- [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)
- [Swift Cross Platform Framework](https://goo.gl/XxaJGo) 👍

**Comment by paulrolfe** [comment]
Thanks, I'll consider it.

**Comment by paulrolfe** [comment]
You are welcome to submit a Pull Request for carthage support, but I've decided I won't be adding this. Thanks for your suggestion.
